alias PYSHS='python -m SimpleHTTPServer'
alias manify='groff -T utf8 -man'

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# some more ls aliases
alias ll='ls -l'
alias la='ls -A'
alias l='ls -CF'

# vim-profile
alias vimp='~/Code/vimfiles/vim-profile'
alias gvimp='~/Code/vimfiles/gvim-profile'
alias viewp='~/Code/vimfiles/view-profile'

if [[ -d ~/.config/bash_aliases.d ]]; then
    source ~/.config/bash_aliases.d/*
fi
