# vim: set ft=sh :
alias PYSHS='python -m SimpleHTTPServer'
alias manify='groff -T utf8 -man'

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# some more ls aliases
alias ll='ls -l'
alias la='ls -A'
alias l='ls -CF'

# ruby
alias rtest='RAILS_ENV=test ruby -I test'
alias brtest='RAILS_ENV=test bundle exec ruby -I test'
alias prtest='RAILS_ENV=test pry -I test'
alias trake="RAILS_ENV=test rake"
alias brake="bundle exec rake"
alias tbrake="RAILS_ENV=test brake"
alias brails="bundle exec rails"
alias tbrails="RAILS_ENV=test brails"

# vim-profile
alias vimp='~/Code/vimfiles/vim-profile'
alias gvimp='~/Code/vimfiles/gvim-profile'
alias viewp='~/Code/vimfiles/view-profile'
alias nvimp='~/Code/vimfiles/nvim-profile'

# Enforce tmux using XDG config dir
# Needed because of https://github.com/tmux/tmux/issues/142
alias tmux='tmux -f ~/.config/tmux/tmux.conf'

if [[ -d ~/.config/bash_aliases.d ]]; then
    for f in `ls ~/.config/bash_aliases.d/*`; do
        source "$f"
    done
    unset f
fi
