# vim: set ft=sh :
alias http='python3 -m http.server'
alias manify='groff -T utf8 -man'
alias reload='source ~/.bashrc'

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    if [[ -r ~/.dircolors ]]; then
        eval "$(dircolors -b ~/.dircolors)"
    else
        eval "$(dircolors -b)"
    fi
    alias ls='ls --color=auto'
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'

    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# some more ls aliases
alias ll='ls -l'
alias la='ls -A'
alias l='ls -CF'

# ruby
alias rtest='RAILS_ENV=test ruby -I test'
alias brtest='RAILS_ENV=test bundle exec ruby -I test'
alias prtest='RAILS_ENV=test pry -I test'
alias trake="RAILS_ENV=test rake"
alias brake="bundle exec rake"
alias tbrake="RAILS_ENV=test brake"
alias brails="bundle exec rails"
alias tbrails="RAILS_ENV=test brails"
alias bexec="bundle exec"
alias brc="bundle exec rails console"
alias brspec="bundle exec rspec"
alias dbundle="BUNDLE_GEMFILE=Gemfile.dev bundle"

# Neovim nightly
if [[ -d /opt/neovim-nightly ]]; then
  alias nnvim="/opt/neovim-nightly/bin/nvim"
fi

# tmate
alias rtmate="tmate -F"

{%- for alias_name, command_value in salt['pillar.get']('bashrc:aliases', {}).items() %}
alias {{ alias_name }}='{{ command_value }}'
{%- endfor %}

if [[ -d ~/.config/bash_aliases.d ]]; then
    for f in ~/.config/bash_aliases.d/*; do
        if [[ -f "$f" ]]; then
          # shellcheck source=/dev/null
          source "$f"
        fi
    done
    unset f
fi
