{%- set pillar_get = salt['pillar.get'] %}
{%- if pillar_get('nushell:enabled') -%}
[nu]
default_features = true
features = ["stable"]
{%- endif %}
{%- if pillar_get('grep-alternative', 'ripgrep') == 'ripgrep' %}
[ripgrep]
toolchain = "nightly"
default_features = true
features = ["simd-accel"]
{%- endif %}
